name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm modules
        run: npm install
      - name: Build with npm
        run: npm run build --if-present
      - name: Test with npm
        run: npm run test --if-present
